version: 1.0.0
type: pipeline
name: "shorthand-pipeline"
body:
  source:
    uri: samples://default

  # `body.states` optional, we can declare tools to execute without any state
  tools:
    - tool: mytool
      extends: testtool
      input: "{{text}}"
