package machinum.workspace;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import machinum.yaml.ToolDefinition;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.ObjectMapper;
import tools.jackson.dataformat.yaml.YAMLFactory;

@Slf4j
@RequiredArgsConstructor
public class WorkspaceInitializerTool {

  private final Path workspaceRoot;

  private final WorkspaceLayout layout;

  //TODO: Use CoreCOnfig Instead
  @Deprecated(forRemoval = true)
  private static final ObjectMapper YAML_MAPPER = new ObjectMapper(new YAMLFactory());

  public void install(boolean force) throws IOException {
    log.info("Starting workspace installation...");
    download();
    bootstrap(force);
    log.info("Workspace installation complete!");
  }

  public void download() {
    log.info("Downloading tool sources...");
    log.debug("Tool download complete (no external tools configured yet)");
  }

  public void bootstrap(boolean force) throws IOException {
    log.info("Bootstrapping workspace...");

    layout.createDirectories();

    generateSeedYaml(force);
    generateToolsYaml(force);

    // Parse tools.yaml and generate package.json if node tools are present
    Path toolsYamlPath = layout.getMtDir().resolve("tools.yaml");
    if (Files.exists(toolsYamlPath)) {
      List<ToolDefinition> nodeTools = parseNodeToolsFromYaml(toolsYamlPath);
      generatePackageJson(nodeTools, force);
    }

    log.info("Bootstrap complete!");
  }

  private void generateSeedYaml(boolean force) throws IOException {
    Path seedPath = workspaceRoot.resolve("seed.yaml");

    if (Files.exists(seedPath) && !force) {
      log.debug("seed.yaml already exists, skipping (use --force to overwrite)");
      return;
    }

    String seedContent = """
        # Machinum Pipeline Root Configuration
        # Generated by machinum install

        version: 1.0.0
        type: root
        name: "My Pipeline Workspace"
        description: "Default workspace configuration"

        body:
          # Tool definitions location
          tools: ".mt/tools.yaml"

          # Execution settings
          execution:
            parallel: false
            resume: true
            manifest-snapshot:
              enabled: true
              mode: copy

          # Error handling
          error-handling:
            retry:
              max-attempts: 3
              backoff:
                type: fixed
                initial-delay: 2s

          # Cleanup policy
          cleanup:
            success: 7d
            failed: 14d
            success-runs: 5
            failed-runs: 10

          # Environment variables
          env-files:
            - ".env"
          env:
            # Add your environment variables here
            # API_KEY: "{{env.OPENAI_API_KEY}}"
        """;

    Files.writeString(seedPath, seedContent);
    log.info("Generated: seed.yaml");
  }

  private void generateToolsYaml(boolean force) throws IOException {
    Path toolsPath = layout.getMtDir().resolve("tools.yaml");

    if (Files.exists(toolsPath) && !force) {
      log.debug("tools.yaml already exists, skipping (use --force to overwrite)");
      return;
    }

    String toolsContent = """
        # Machinum Tool Definitions
        # Generated by machinum install

        version: 1.0.0
        type: tools
        name: "Default Toolset"
        description: "Example tool configurations"

        body:
          # Execution targets
          execution-targets:
            default: local
            targets:
              - name: local
                type: local

          # Install-phase tools
          install:
            tools:
              - name: workspace-init
                phase: bootstrap_only
                tool: workspace-init

          # Tool definitions
          tools:
            # Example: Internal tool (SPI-based)
            - name: peek
              type: internal
              description: "Log input for debugging"
              config:
                log-level: info

            # Example: External shell script
            - name: uppercase-transformer
              type: external
              runtime: shell
              description: "Convert text to uppercase"
              source:
                type: file
                url: ".mt/scripts/transformers/uppercase.sh"
              timeout: 30s
              config:
                work-dir: "{{rootDir}}"

            # Example: External Groovy script
            - name: text-validator
              type: external
              runtime: groovy
              description: "Validate text content"
              source:
                type: file
                url: ".mt/scripts/validators/not_empty.groovy"
              timeout: 10s
              config:
                return-type: Boolean
        """;

    Files.writeString(toolsPath, toolsContent);
    log.info("Generated: .mt/tools.yaml");
  }

  @SuppressWarnings("unchecked")
  private List<ToolDefinition> parseNodeToolsFromYaml(Path toolsYamlPath) {
    List<ToolDefinition> nodeTools = new ArrayList<>();

    try {
      JsonNode root = YAML_MAPPER.readTree(toolsYamlPath.toFile());
      JsonNode bodyNode = root.path("body");

      // Check install-phase tools
      JsonNode installNode = bodyNode.path("install");
      parseToolsFromSection(installNode, nodeTools);

      // Check regular tools section
      JsonNode toolsNode = bodyNode.path("tools");
      parseToolsFromSection(toolsNode, nodeTools);
    } catch (Exception e) {
      log.warn("Failed to parse tools.yaml for node tools: {}", e.getMessage());
    }

    return nodeTools;
  }

  @SuppressWarnings("unchecked")
  private void parseToolsFromSection(JsonNode sectionNode, List<ToolDefinition> nodeTools) {
    if (!sectionNode.isArray()) {
      return;
    }

    for (JsonNode toolNode : sectionNode) {
      String runtime = toolNode.path("runtime").asText("");
      String type = toolNode.path("type").asText("");

      // Detect node tools by runtime or type
      if ("node".equalsIgnoreCase(runtime) || "node".equalsIgnoreCase(type)) {
        String name = toolNode.path("name").asText();
        if (!name.isEmpty()) {
          JsonNode configNode = toolNode.path("config");
          Map<String, Object> config = configNode.isMissingNode() || configNode.isNull()
              ? Map.of()
              : YAML_MAPPER.convertValue(configNode, Map.class);

          // Extract version if present
          if (toolNode.has("version")) {
            config = new HashMap<>(config);
            config.put("version", toolNode.path("version").asText());
          }

          ToolDefinition def = ToolDefinition.builder()
              .name(name)
              .type("node")
              .toolConfig(config)
              .build();

          nodeTools.add(def);
        }
      }
    }
  }

  public void generatePackageJson(List<ToolDefinition> nodeTools, boolean force)
      throws IOException {
    Path packagePath = workspaceRoot.resolve("package.json");

    if (Files.exists(packagePath) && !force) {
      log.debug("package.json already exists, skipping (use --force to overwrite)");
      return;
    }

    if (nodeTools == null || nodeTools.isEmpty()) {
      log.debug("No node tools declared, skipping package.json generation");
      return;
    }

    StringBuilder depsBuilder = new StringBuilder();
    for (ToolDefinition tool : nodeTools) {
      String version = (String) tool.toolConfig().getOrDefault("version", "latest");
      String name = tool.name();
      depsBuilder.append("    \"").append(name).append("\": \"").append(version).append("\",\n");
    }

    String deps =
        depsBuilder.length() > 0 ? depsBuilder.substring(0, depsBuilder.length() - 2) : "";

    String packageContent = """
        {
          "name": "machinum-workspace",
          "version": "1.0.0",
          "description": "Machinum Pipeline workspace with Node.js tools",
          "private": true,
          "dependencies": {
        %s
          }
        }
        """.formatted(deps);

    Files.writeString(packagePath, packageContent);
    log.info("Generated: package.json with {} node tool(s)", nodeTools.size());
  }

  @Deprecated(forRemoval = true)
  public boolean isInitialized() {
    return Files.exists(layout.getMtDir())
        && Files.exists(layout.getChaptersDir())
        && Files.exists(layout.getManifestsDir());
  }
}
