package machinum.workspace;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import machinum.yaml.ToolDefinition;

/**
 * Initializes workspace with download and bootstrap phases.
 *
 * <p>Phases:
 *
 * <ul>
 *   <li>download - Fetches tool sources without mutating workspace layout
 *   <li>bootstrap - Creates directory structure and generates configuration files
 * </ul>
 */
@Slf4j
@RequiredArgsConstructor
public class WorkspaceInitializerTool {

  /** Workspace root directory. */
  private final Path workspaceRoot;

  /** Workspace layout helper. */
  private final WorkspaceLayout layout;

  /**
   * Runs full installation: download → bootstrap.
   *
   * @param force if true, overwrite existing files
   * @throws IOException if initialization fails
   */
  public void install(boolean force) throws IOException {
    log.info("Starting workspace installation...");
    download();
    bootstrap(force);
    log.info("Workspace installation complete!");
  }

  /**
   * Downloads tool sources without mutating workspace layout.
   *
   * @throws IOException if download fails
   */
  public void download() throws IOException {
    log.info("Downloading tool sources...");
    // For MVP: This is a placeholder - actual tool downloading will be implemented
    // when tool registry with git/http sources is available
    log.debug("Tool download complete (no external tools configured yet)");
  }

  /**
   * Bootstraps workspace by creating directory structure and generating files.
   *
   * @param force if true, overwrite existing files
   * @throws IOException if bootstrap fails
   */
  public void bootstrap(boolean force) throws IOException {
    log.info("Bootstrapping workspace...");

    // Create directory structure
    layout.createDirectories();

    // Generate configuration files
    generateSeedYaml(force);
    generateToolsYaml(force);

    log.info("Bootstrap complete!");
  }

  /**
   * Generates seed.yaml configuration file.
   *
   * @param force if true, overwrite existing file
   * @throws IOException if generation fails
   */
  private void generateSeedYaml(boolean force) throws IOException {
    Path seedPath = workspaceRoot.resolve("seed.yaml");

    if (Files.exists(seedPath) && !force) {
      log.debug("seed.yaml already exists, skipping (use --force to overwrite)");
      return;
    }

    String seedContent = """
        # Machinum Pipeline Root Configuration
        # Generated by machinum install

        version: 1.0.0
        type: root
        name: "My Pipeline Workspace"
        description: "Default workspace configuration"

        body:
          # Tool definitions location
          tools: ".mt/tools.yaml"

          # Execution settings
          execution:
            parallel: false
            resume: true
            manifest-snapshot:
              enabled: true
              mode: copy

          # Error handling
          error-handling:
            retry:
              max-attempts: 3
              backoff:
                type: fixed
                initial-delay: 2s

          # Cleanup policy
          cleanup:
            success: 7d
            failed: 14d
            success-runs: 5
            failed-runs: 10

          # Environment variables
          env-files:
            - ".env"
          env:
            # Add your environment variables here
            # API_KEY: "{{env.OPENAI_API_KEY}}"
        """;

    Files.writeString(seedPath, seedContent);
    log.info("Generated: seed.yaml");
  }

  /**
   * Generates .mt/tools.yaml configuration file.
   *
   * @param force if true, overwrite existing file
   * @throws IOException if generation fails
   */
  private void generateToolsYaml(boolean force) throws IOException {
    Path toolsPath = layout.getMtDir().resolve("tools.yaml");

    if (Files.exists(toolsPath) && !force) {
      log.debug("tools.yaml already exists, skipping (use --force to overwrite)");
      return;
    }

    String toolsContent = """
        # Machinum Tool Definitions
        # Generated by machinum install

        version: 1.0.0
        type: tools
        name: "Default Toolset"
        description: "Example tool configurations"

        body:
          # Execution targets
          execution-targets:
            default: local
            targets:
              - name: local
                type: local

          # Install-phase tools
          install:
            tools:
              - name: workspace-init
                phase: bootstrap_only
                tool: workspace-init

          # Tool definitions
          tools:
            # Example: Internal tool (SPI-based)
            - name: peek
              type: internal
              description: "Log input for debugging"
              config:
                log-level: info

            # Example: External shell script
            - name: uppercase-transformer
              type: external
              runtime: shell
              description: "Convert text to uppercase"
              source:
                type: file
                url: ".mt/scripts/transformers/uppercase.sh"
              timeout: 30s
              config:
                work-dir: "{{rootDir}}"

            # Example: External Groovy script
            - name: text-validator
              type: external
              runtime: groovy
              description: "Validate text content"
              source:
                type: file
                url: ".mt/scripts/validators/not_empty.groovy"
              timeout: 10s
              config:
                return-type: Boolean
        """;

    Files.writeString(toolsPath, toolsContent);
    log.info("Generated: .mt/tools.yaml");
  }

  /**
   * Generates package.json if node tools are declared.
   *
   * @param nodeTools list of node tool definitions
   * @param force if true, overwrite existing file
   * @throws IOException if generation fails
   */
  public void generatePackageJson(List<ToolDefinition> nodeTools, boolean force)
      throws IOException {
    Path packagePath = workspaceRoot.resolve("package.json");

    if (Files.exists(packagePath) && !force) {
      log.debug("package.json already exists, skipping (use --force to overwrite)");
      return;
    }

    if (nodeTools == null || nodeTools.isEmpty()) {
      log.debug("No node tools declared, skipping package.json generation");
      return;
    }

    // Build dependencies map
    StringBuilder depsBuilder = new StringBuilder();
    for (ToolDefinition tool : nodeTools) {
      // Extract version from tool config
      String version = (String) tool.toolConfig().getOrDefault("version", "latest");
      String name = tool.name();
      depsBuilder.append("    \"").append(name).append("\": \"").append(version).append("\",\n");
    }

    // Remove trailing comma and newline
    String deps =
        depsBuilder.length() > 0 ? depsBuilder.substring(0, depsBuilder.length() - 2) : "";

    String packageContent = """
        {
          "name": "machinum-workspace",
          "version": "1.0.0",
          "description": "Machinum Pipeline workspace with Node.js tools",
          "private": true,
          "dependencies": {
        """ + deps + """

          }
        }
        """;

    Files.writeString(packagePath, packageContent);
    log.info("Generated: package.json with {} node tool(s)", nodeTools.size());
  }

  /**
   * Checks if workspace is already initialized.
   *
   * @return true if workspace structure exists
   */
  public boolean isInitialized() {
    return Files.exists(layout.getMtDir())
        && Files.exists(layout.getChaptersDir())
        && Files.exists(layout.getManifestsDir());
  }
}
