# Application configuration file. See https://github.com/typesafehub/config/blob/master/HOCON.md for more details

application.env=dev
server.port=7071

# ===== #

server.port=${?SERVER_PORT}
# application.env=${?APPLICATION_ENV}


# server.ioThreads: Number of IO threads (Netty/Undertow). Defaults to Processors * 2.
# server.workerThreads: Number of worker threads. Defaults to ioThreads * 8.
# server.maxRequestSize: Maximum request size in bytes. Exceeding this triggers a 413 Request Entity Too Large response.
# server.defaultHeaders: Automatically sets Date, Content-Type, and Server headers.
# server.expectContinue: Enables support for 100-Continue requests.